port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_4, server: a.gfw.services, port: 64739, type: ss, cipher: chacha20-ietf-poly1305, password: abc9a8de-024e-42ea-b1f3-b9ea7a85f9ed}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_5, server: a.gfw.services, port: 21566, type: ss, cipher: chacha20-ietf-poly1305, password: abc9a8de-024e-42ea-b1f3-b9ea7a85f9ed}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_6, server: hcmfast.fuzzyng.net, port: 80, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_7, server: hcmfly.fuzzyng.net, port: 80, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_8, server: hcm.fuzzyng.net, port: 80, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_9, server: hn2.fuzzyng.net, port: 80, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_10, server: hn03.fuzzyng.net, port: 80, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_11, server: hn02.fuzzyng.net, port: 80, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_12, server: hn01.fuzzyng.net, port: 80, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_13, server: cf-lt.sharecentre.online, port: 80, type: vmess, uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp4.scproxy.top}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_14, server: jp.fuzzypn.me, port: 443, type: vmess, uuid: a1a2cfbe-ba38-429d-a31d-ce94cd50cae6, alterId: 0, cipher: auto, tls: true, network: grpc, servername: fuzzypn, grpc-opts: {grpc-service-name: /}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_15, server: inf.314156.xyz, port: 80, type: vmess, uuid: 5b3b5d3f-68a1-4afe-8a9e-a55f30af98e3, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /workerConfig, headers: {Host: inf.314156.xyz}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_16, server: gzzz.8bqyato.ml, port: 41033, type: vmess, uuid: c7a1f42c-c79a-3c31-9544-89aff988379c, alterId: 0, cipher: auto, tls: false}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_17, server: gzzz.8bqyato.ml, port: 41034, type: vmess, uuid: c7a1f42c-c79a-3c31-9544-89aff988379c, alterId: 0, cipher: auto, tls: false}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_18, server: gzzz.8bqyato.ml, port: 41032, type: vmess, uuid: c7a1f42c-c79a-3c31-9544-89aff988379c, alterId: 0, cipher: auto, tls: false}
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_4
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_5
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_6
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_7
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_8
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_9
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_10
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_11
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_12
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_13
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_14
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_15
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_16
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_17
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_18
rules:
 - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
