port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: https://github.com/Alvin9999/new-pac/wiki ip, server: sz.cny.page, port: 11536, type: ss, cipher: aes-128-gcm, password: 2cfc4c58-88cb-4e00-9977-ef0a37559a22}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 2, server: sz.cny.page, port: 32366, type: ss, cipher: aes-128-gcm, password: 2cfc4c58-88cb-4e00-9977-ef0a37559a22}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 3, server: sz.cny.page, port: 25984, type: ss, cipher: aes-128-gcm, password: 2cfc4c58-88cb-4e00-9977-ef0a37559a22}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 4, server: cdn.gcup.wiki, port: 2053, type: vmess, uuid: da12affb-2953-4b35-9677-f85d9743d9c4, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /freegcup, headers: {Host: kr.gcup.wiki}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 5, server: ah-cm.cmcclives.top, port: 58469, type: vmess, uuid: 8e328e84-2845-4f13-b521-78ddb79c9f3b, alterId: 0, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 6, server: 140.99.59.253, port: 55512, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - https://github.com/Alvin9999/new-pac/wiki ip
      - https://github.com/Alvin9999/new-pac/wiki ip 2
      - https://github.com/Alvin9999/new-pac/wiki ip 3
      - https://github.com/Alvin9999/new-pac/wiki ip 4
      - https://github.com/Alvin9999/new-pac/wiki ip 5
      - https://github.com/Alvin9999/new-pac/wiki ip 6
rules:
 - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
