port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-9CDN, server: 198.41.203.7, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-8CDN, server: 188.114.99.10, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-7CDN, server: 203.30.191.11, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-6CDN, server: 141.101.114.2, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-5CDN, server: 141.101.115.100, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-4CDN, server: 198.41.212.150, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-3CDN, server: 141.101.115.120, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-2CDN, server: 141.101.114.150, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-16CDN, server: 185.162.228.229, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-15CDN, server: 23.227.38.107, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-14CDN, server: 203.24.108.100, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-12CDN, server: 203.30.189.1, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-11CDN, server: 203.30.190.1, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-10CDN, server: 23.227.38.39, port: 80, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: lg.v2ray8.xyz}}}
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-9CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-8CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-7CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-6CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-5CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-4CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-3CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-2CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-16CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-15CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-14CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-12CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-11CDN
      - ğŸ‡ºğŸ‡¸ https://github.com/Alvin9999/new-pac/wiki clash ip6 æ´›æ‰çŸ¶1-10CDN
rules:
 - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
