port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com, server: sw.tbstbstbstbs666.com, port: 18823, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 2, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: buyvm2.yxjnode.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 3, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: buyvm1.yxjnode.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 4, server: yx.timeswath.uk, port: 80, type: vmess, uuid: 947bfda6-877f-4747-8e89-da77a0eef191, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /111111111, headers: {Host: sfo.fof124.top}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 5, server: sw.tbstbstbstbs666.com, port: 18812, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 6, server: sw.tbstbstbstbs666.com, port: 18820, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 7, server: sw.tbstbstbstbs666.com, port: 18839, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 8, server: sw.tbstbstbstbs666.com, port: 18829, type: vmess, uuid: 29d5b05b-9166-3981-be60-a2561d1aa95d, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: sw.tbstbstbstbs666.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 9, server: tls2.fuzzyng.net, port: 443, type: vmess, uuid: ec7c94b5-6ca6-4289-b44b-c6583f2c5f6c, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: "/fuzzyng?ed=2048", headers: {Host: dl.kgvn.garenanow.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 10, server: cf-lt.sharecentre.online, port: 80, type: vmess, uuid: 2d5d8b9c-8ec4-4a37-b610-78e71e13eaef, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: dp4.scproxy.top}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 11, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: dp2.yxjnode.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 12, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: dp1.yxjnode.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 13, server: cf.yxjnode.com, port: 80, type: vmess, uuid: 09c1d32d-4458-4ebf-b36d-4dd732bae3aa, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /yxzbp, headers: {Host: dp3.yxjnode.com}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 14, server: 59.36.84.180, port: 63092, type: vmess, uuid: 311f3c4b-90a1-3c5c-a4fe-215cc7c90d02, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: 59.36.84.180}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 15, server: inf.314156.xyz, port: 80, type: vmess, uuid: 5b3b5d3f-68a1-4afe-8a9e-a55f30af98e3, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /workerConfig, headers: {Host: inf.314156.xyz}}}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 16, server: a.gfw.services, port: 64739, type: ss, cipher: chacha20-ietf-poly1305, password: abc9a8de-024e-42ea-b1f3-b9ea7a85f9ed}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 17, server: ahcm.v-too.cloud, port: 10259, type: ss, cipher: chacha20-ietf-poly1305, password: 75c9c41d-5287-4b13-abe4-c66a8c0ab9f4}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 18, server: a.gfw.services, port: 21566, type: ss, cipher: chacha20-ietf-poly1305, password: abc9a8de-024e-42ea-b1f3-b9ea7a85f9ed}
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 2
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 3
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 4
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 5
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 6
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 7
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 8
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 9
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 10
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 11
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 12
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 13
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 14
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 15
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 16
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 17
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com 18
rules:
 - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
