port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: https://github.com/Alvin9999/new-pac/wiki ip, server: 198.2.208.184, port: 35402, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 2, server: 167.88.63.79, port: 443, type: ss, cipher: aes-256-gcm, password: pKEW8JPByTVTLtM}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 3, server: 167.88.63.79, port: 8881, type: ss, cipher: aes-256-gcm, password: kDWvXYZoTBcGkC4}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 4, server: 167.88.63.79, port: 8119, type: ss, cipher: aes-256-gcm, password: cdBIDV42DCwnfIN}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 5, server: 167.88.63.79, port: 3389, type: ss, cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 6, server: 167.88.63.79, port: 7307, type: ss, cipher: aes-256-gcm, password: FoOiGlkAA9yPEGP}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 7, server: 167.88.63.79, port: 8118, type: ss, cipher: aes-256-gcm, password: cdBIDV42DCwnfIN}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 8, server: 167.88.63.79, port: 5003, type: ss, cipher: aes-256-gcm, password: g5MeD6Ft3CWlJId}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 9, server: 172.67.86.87, port: 80, type: vmess, uuid: 2e496758-950e-4549-8842-d5eec98d9fde, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /shirker, headers: {Host: uk1.scproxy.top}}}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 10, server: 45.129.3.99, port: 11111, type: ss, cipher: aes-256-gcm, password: dongtaiwang.com}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 11, server: sz.cny.page, port: 11536, type: ss, cipher: aes-128-gcm, password: 2cfc4c58-88cb-4e00-9977-ef0a37559a22}
  - {name: https://github.com/Alvin9999/new-pac/wiki ip 12, server: 140.99.59.253, port: 55512, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
proxy-groups:
  - name: üî∞ ËäÇÁÇπÈÄâÊã©
    type: select
    proxies:
      - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - https://github.com/Alvin9999/new-pac/wiki ip
      - https://github.com/Alvin9999/new-pac/wiki ip 2
      - https://github.com/Alvin9999/new-pac/wiki ip 3
      - https://github.com/Alvin9999/new-pac/wiki ip 4
      - https://github.com/Alvin9999/new-pac/wiki ip 5
      - https://github.com/Alvin9999/new-pac/wiki ip 6
      - https://github.com/Alvin9999/new-pac/wiki ip 7
      - https://github.com/Alvin9999/new-pac/wiki ip 8
      - https://github.com/Alvin9999/new-pac/wiki ip 9
      - https://github.com/Alvin9999/new-pac/wiki ip 10
      - https://github.com/Alvin9999/new-pac/wiki ip 11
      - https://github.com/Alvin9999/new-pac/wiki ip 12
rules:
 - MATCH,üî∞ ËäÇÁÇπÈÄâÊã©
