port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_1, server: cn-shcm.cat-input.com, port: 8210, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: us-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_2, server: cn-shcm.cat-input.com, port: 9210, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: SG-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_3, server: f1e8571e-fbd9-4023-a7af-e7a187ce3a14.ens4.buzz, port: 47550, type: trojan, password: 42b99403-2702-4163-8878-92f853a8f0e3, sni: apps.apple.com, skip-cert-verify: true}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_4, server: cn-shcu.cat-input.com, port: 8300, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: us-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_5, server: cn-shcu.cat-input.com, port: 8210, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: us-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_6, server: cn-shcu.cat-input.com, port: 9300, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hinet-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_7, server: iepl00.cat-input.com, port: 20012, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: us-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_8, server: iepl02.cat-input.com, port: 20007, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: us-02.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_9, server: f154b9cd-6b31-4bfd-a574-b1cdab76c061.ens4.buzz, port: 31508, type: trojan, password: 42b99403-2702-4163-8878-92f853a8f0e3, sni: apps.apple.com, skip-cert-verify: true}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_10, server: cn-shcm.cat-input.com, port: 9420, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_11, server: 5b4c27a7-ae6c-43d4-87b7-df6ad808b463.ens4.buzz, port: 34013, type: trojan, password: 42b99403-2702-4163-8878-92f853a8f0e3, sni: apps.apple.com, skip-cert-verify: true}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_12, server: cn-shcm.cat-input.com, port: 9300, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hinet-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_13, server: cn-shcm.cat-input.com, port: 9415, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_14, server: cn-shcu.cat-input.com, port: 9420, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_15, server: cn-bj.cat-input.com, port: 9415, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_16, server: 2ee9304c-7a01-4286-963d-4624059e4054.ens4.buzz, port: 29446, type: trojan, password: 42b99403-2702-4163-8878-92f853a8f0e3, sni: apps.apple.com, skip-cert-verify: true}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_17, server: cn-fs.cat-input.com, port: 9415, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_18, server: cn-shcm.cat-input.com, port: 9140, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hkt-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_19, server: cn-shcu.cat-input.com, port: 9415, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_20, server: cn-cqcm.cat-input.com, port: 9150, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: cmhk-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_21, server: iepl01.cat-input.com, port: 20030, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_22, server: dd5d3b70-70da-4751-a68b-eb26cae92a3b.ens4.buzz, port: 53919, type: trojan, password: 42b99403-2702-4163-8878-92f853a8f0e3, sni: apps.apple.com, skip-cert-verify: true}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_23, server: cn-fs.cat-input.com, port: 9140, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hkt-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_24, server: cn-bj.cat-input.com, port: 9310, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hinet-02.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_25, server: cn-shcu.cat-input.com, port: 9135, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hkbn-02.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_26, server: cn-shcu.cat-input.com, port: 9405, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_27, server: cn-bj.cat-input.com, port: 9405, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_28, server: iepl02.cat-input.com, port: 20030, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_29, server: cn-ahcm.cat-input.com, port: 9310, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hinet-02.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_30, server: iepl01.cat-input.com, port: 20038, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: cmhk-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_31, server: cn-cqcm.cat-input.com, port: 9120, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hkcmi-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_32, server: iepl01.cat-input.com, port: 20021, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hinet-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_33, server: iepl00.cat-input.com, port: 20010, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: cmhk-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_34, server: iepl00.cat-input.com, port: 20008, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hinet-02.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_35, server: iepl02.cat-input.com, port: 20038, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: cmhk-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_36, server: iepl02.cat-input.com, port: 20021, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: hinet-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_37, server: cn-bj.cat-input.com, port: 9210, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: SG-03.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_38, server: cn-ah.cat-input.com, port: 8310, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: us-02.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_39, server: cn-cqcm.cat-input.com, port: 9405, type: trojan, password: 6c74f352-c5e3-43ae-abfa-4b9750085b74, sni: JP-01.oneok.link}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_40, server: 41a4d0b0-88df-4664-81a1-4e4403d478b2.ens4.buzz, port: 39547, type: trojan, password: 42b99403-2702-4163-8878-92f853a8f0e3, sni: apps.apple.com, skip-cert-verify: true}
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_1
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_2
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_3
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_4
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_5
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_6
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_7
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_8
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_9
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_10
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_11
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_12
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_13
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_14
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_15
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_16
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_17
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_18
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_19
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_20
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_21
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_22
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_23
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_24
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_25
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_26
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_27
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_28
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_29
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_30
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_31
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_32
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_33
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_34
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_35
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_36
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_37
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_38
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_39
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_40
rules:
 - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
