port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_1, server: iepl.bj-bj.cyou, port: 36611, type: ss, cipher: aes-128-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_2, server: gb-service.bygcloud.xyz, port: 27003, type: ss, cipher: aes-128-gcm, password: 0611fb89-6e48-4a40-abdb-c883fb68caff}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_3, server: iepl.bj-bj.cyou, port: 36601, type: ss, cipher: aes-256-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_4, server: iepl.bj-bj.cyou, port: 36611, type: ss, cipher: aes-128-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_5, server: gb-service.bygcloud.xyz, port: 27022, type: ss, cipher: aes-128-gcm, password: 0611fb89-6e48-4a40-abdb-c883fb68caff}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_6, server: iepl.bj-bj.cyou, port: 36601, type: ss, cipher: aes-256-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_7, server: ahcm.v-too.cloud, port: 10259, type: ss, cipher: chacha20-ietf-poly1305, password: 6b6841eb-6de7-4fc7-b00c-34a02ebc17bd}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_8, server: iepl.bj-bj.cyou, port: 36611, type: ss, cipher: aes-128-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_9, server: ahcm.v-too.cloud, port: 10259, type: ss, cipher: chacha20-ietf-poly1305, password: 6b6841eb-6de7-4fc7-b00c-34a02ebc17bd}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_10, server: iepl.bj-bj.cyou, port: 36611, type: ss, cipher: aes-128-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_11, server: fscm.v-too.cloud, port: 21262, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_12, server: fscm.v-too.cloud, port: 24353, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_13, server: iepl.bj-bj.cyou, port: 36601, type: ss, cipher: aes-256-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_14, server: iepl.bj-bj.cyou, port: 36601, type: ss, cipher: aes-256-gcm, password: ccf9a4a3-5877-433d-a021-82d0bff433f1}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_15, server: gb-service.bygcloud.xyz, port: 27019, type: ss, cipher: aes-128-gcm, password: 0611fb89-6e48-4a40-abdb-c883fb68caff}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_16, server: fscm.v-too.cloud, port: 24353, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_17, server: fscm.v-too.cloud, port: 21262, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_18, server: gb-service.bygcloud.xyz, port: 27020, type: ss, cipher: aes-128-gcm, password: 0611fb89-6e48-4a40-abdb-c883fb68caff}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_19, server: fscm.v-too.cloud, port: 24353, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_20, server: gb-service.bygcloud.xyz, port: 23001, type: ss, cipher: aes-128-gcm, password: 0611fb89-6e48-4a40-abdb-c883fb68caff}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_21, server: fscm.v-too.cloud, port: 24353, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_22, server: fscm.v-too.cloud, port: 21262, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_23, server: gb-service.bygcloud.xyz, port: 23002, type: ss, cipher: aes-128-gcm, password: 0611fb89-6e48-4a40-abdb-c883fb68caff}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_24, server: gb-service.bygcloud.xyz, port: 22001, type: ss, cipher: aes-128-gcm, password: 0611fb89-6e48-4a40-abdb-c883fb68caff}
  - {name: ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_25, server: fscm.v-too.cloud, port: 21262, type: ss, cipher: chacha20-ietf-poly1305, password: f21a1359-79b4-44dd-9a70-d6b9b19beb14}
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_1
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_2
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_3
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_4
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_5
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_6
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_7
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_8
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_9
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_10
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_11
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_12
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_13
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_14
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_15
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_16
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_17
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_18
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_19
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_20
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_21
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_22
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_23
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_24
      - ğŸ‡¨ğŸ‡³ www.dongtaiwang.com_25
rules:
 - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
