port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-5, server: 198.41.203.6, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-4, server: 141.101.115.100, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-3, server: 198.41.212.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-20, server: 185.162.228.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-2, server: 141.101.114.111, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-19, server: 66.235.200.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-18, server: 203.24.108.8, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-17, server: 203.30.188.1, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr1.v2ray5.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-16, server: 203.30.189.2, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-15, server: 203.30.190.2, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-14, server: 23.227.38.38, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-13, server: 188.114.99.9, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-12, server: 203.30.191.2, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
  - {name: ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1, server: 141.101.115.111, port: 80, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: fr.v2ray9.xyz}}}
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-5
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-4
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-3
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-20
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-2
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-19
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-18
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-17
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-16
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-15
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-14
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-13
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1-12
      - ğŸ‡«ğŸ‡· https://github.com/Alvin9999/new-pac/wiki clash ip5 æ³•å›½CDN1
rules:
 - MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
